[tool.poetry]
name = "riot-match-service"
version = "0.1.0"
description = "League of Legends match analytics service using Riot API"
authors = ["Anna Veselova"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.127.0"
uvicorn = { extras = ["standard"], version = "^0.44" }
sqlalchemy = "^2.0.46"
asyncpg = "^0.31.0"
alembic = "^1.18.4"
psycopg = {extras = ["binary"], version = "^3.3.3"}
pydantic = {extras = ["mypy"], version = "^2.12"}
pydantic-settings = "^2.12"
httpx = "^0.28.1"
python-dotenv = "^1.2.2"
orjson = "^3.11.9"
aiolimiter = "^1.2.1"


[tool.poetry.group.dev.dependencies]
isort = "^8.0.1"
flake8 = "^7.3.0"
flake8-quotes = "^3.4.0"
mypy = "^2.1.0"
pre-commit = "^4.6.0"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.11"
plugins = ["pydantic.mypy"]
exclude = "alembic/versions/.*\\.py$"

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
