"""update player with tracked and synced

Revision ID: 0d3bf64504a6
Revises: de7710c6ff5f
Create Date: 2026-05-25 09:38:10.821503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d3bf64504a6'
down_revision: Union[str, Sequence[str], None] = 'de7710c6ff5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_participants', 'team_position',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_constraint(op.f('match_participants_player_puuid_fkey'), 'match_participants', type_='foreignkey')
    op.create_foreign_key(None, 'match_participants', 'players', ['player_puuid'], ['puuid'])
    op.add_column('players', sa.Column('is_tracked', sa.Boolean(), nullable=False))
    op.add_column('players', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('players', 'game_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('players', 'tag_line',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('players', 'summoner_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'profile_icon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_players_is_tracked'), 'players', ['is_tracked'], unique=False)
    op.drop_column('players', 'raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_players_is_tracked'), table_name='players')
    op.alter_column('players', 'profile_icon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'summoner_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'tag_line',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('players', 'game_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('players', 'last_synced_at')
    op.drop_column('players', 'is_tracked')
    op.drop_constraint(None, 'match_participants', type_='foreignkey')
    op.create_foreign_key(op.f('match_participants_player_puuid_fkey'), 'match_participants', 'players', ['player_puuid'], ['puuid'], ondelete='CASCADE')
    op.alter_column('match_participants', 'team_position',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
