"""update models

Revision ID: 4ca57ca63eaa
Revises: 0d3bf64504a6
Create Date: 2026-05-27 11:21:42.516299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca57ca63eaa'
down_revision: Union[str, Sequence[str], None] = '0d3bf64504a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_participants', 'match_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_match_participant_match_player'), 'match_participants', type_='unique')
    op.create_unique_constraint('uq_match_player_match_participant', 'match_participants', ['player_puuid', 'match_id'])
    op.alter_column('matches', 'match_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('ranked_entries', 'rank',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranked_entries', 'rank',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('matches', 'match_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint('uq_match_player_match_participant', 'match_participants', type_='unique')
    op.create_unique_constraint(op.f('uq_match_participant_match_player'), 'match_participants', ['match_id', 'player_puuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('match_participants', 'match_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
