"""init models

Revision ID: c55c6e2f01d4
Revises: 
Create Date: 2026-05-23 11:34:59.960430

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c55c6e2f01d4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_mode', sa.String(length=32), nullable=False),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_patch'), 'matches', ['patch'], unique=False)
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_index(op.f('ix_matches_started_at'), 'matches', ['started_at'], unique=False)
    op.create_table('players',
    sa.Column('puuid', sa.String(length=90), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('tag_line', sa.Text(), nullable=False),
    sa.Column('summoner_level', sa.Integer(), nullable=False),
    sa.Column('profile_icon_id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index('ix_players_game_name_tag_line', 'players', ['game_name', 'tag_line'], unique=False)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('player_puuid', sa.String(length=90), nullable=False),
    sa.Column('champion_name', sa.String(length=40), nullable=False),
    sa.Column('team_position', sa.String(length=30), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=False),
    sa.Column('creep_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_puuid', name='uq_match_participant_match_player')
    )
    op.create_index('ix_match_participant_player_champion', 'match_participants', ['player_puuid', 'champion_name'], unique=False)
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_table('ranked_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_puuid', sa.String(length=90), nullable=False),
    sa.Column('queue_type', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.String(length=8), nullable=False),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_puuid', 'queue_type', name='uq_ranked_entry_player_queue')
    )
    op.create_index(op.f('ix_ranked_entries_player_puuid'), 'ranked_entries', ['player_puuid'], unique=False)
    op.create_index(op.f('ix_ranked_entries_queue_type'), 'ranked_entries', ['queue_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranked_entries_queue_type'), table_name='ranked_entries')
    op.drop_index(op.f('ix_ranked_entries_player_puuid'), table_name='ranked_entries')
    op.drop_table('ranked_entries')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_index('ix_match_participant_player_champion', table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index('ix_players_game_name_tag_line', table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_started_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_patch'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
