"""add some fields

Revision ID: de7710c6ff5f
Revises: c55c6e2f01d4
Create Date: 2026-05-24 18:11:17.503201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7710c6ff5f'
down_revision: Union[str, Sequence[str], None] = 'c55c6e2f01d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('gold_spent', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('game_patch', sa.String(length=16), nullable=False))
    op.add_column('matches', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_matches_patch'), table_name='matches')
    op.create_index(op.f('ix_matches_ended_at'), 'matches', ['ended_at'], unique=False)
    op.create_index(op.f('ix_matches_game_patch'), 'matches', ['game_patch'], unique=False)
    op.drop_column('matches', 'game_version')
    op.drop_column('matches', 'patch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('patch', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('game_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_matches_game_patch'), table_name='matches')
    op.drop_index(op.f('ix_matches_ended_at'), table_name='matches')
    op.create_index(op.f('ix_matches_patch'), 'matches', ['patch'], unique=False)
    op.drop_column('matches', 'ended_at')
    op.drop_column('matches', 'game_patch')
    op.drop_column('match_participants', 'gold_spent')
    # ### end Alembic commands ###
